global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']  # Use service name, not hostname

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-expoter:9100']  # Use exporter service name

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Scrape Prometheus itself
